apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  replicas: 1
  selector:
    matchLabels:
      name: post-pod
  template:
    metadata:
      name: post
      labels:
        name: post-pod
        tier: back-end
    spec:
      containers:
        - name: postandcomment-post
          image: tajpouria/postandcomment-post
          env:
            - name: SERVICE_NAME
              value: "post-service"
            - name: PORT
              value: "4000"
            - name: DB_URL
              value: "mongodb://db-clusterip:27017/post"
            - name: EVENT_BROKER
              value: '{ "hostname": "event-broker-clusterIP", "port": 4005, "path": "/" }'
---
apiVersion: v1
kind: Service
metadata:
  name: post-clusterip
spec:
  selector:
    name: post-pod
  ports:
    - targetPort: 4000
      port: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: post-nodeport
spec:
  type: NodePort
  selector:
    name: post-pod
  ports:
    - targetPort: 4000
      port: 4000
      nodePort: 30008

