apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
spec:
  replicas: 1
  selector:
    matchLabels:
      name: query-pod
  template:
    metadata:
      name: query
      labels:
        name: query-pod
        tier: back-end
    spec:
      containers:
        - name: postandcomment-query
          image: tajpouria/postandcomment-query
          env:
            - name: SERVICE_NAME
              value: "query-service"
            - name: PORT
              value: "4002"
            - name: DB_URL
              value: "mongodb://db-clusterip:27017/query"
            - name: EVENT_BROKER
              value: '{ "hostname": "event-broker-clusterIP", "port": 4005, "path": "/" }'
---
apiVersion: v1
kind: Service
metadata:
  name: query-clusterip
spec:
  selector:
    name: query-pod
  ports:
    - targetPort: 4002
      port: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: query-nodeport
spec:
  type: NodePort
  selector:
    name: query-pod
  ports:
    - targetPort: 4002
      port: 4002
      nodePort: 30010

